---
- hosts: all
  become: yes
  roles:
    - role: base
      tags: base

    - role: laptop
      tags: laptop

    - role: macbook
      tags: macbook
      when: "'MacBook' in ansible_product_name"

    - role: openstack-clients
      tags: openstack-clients

    - role: ssh
      tags: ssh

    - role: vim
      tags: vim

    - role: user
      tags: user

    - role: aussie-addons
      tags: aussie-addons
      become_user: "{{ user.name }}"

    - role: openstack-creds
      tags: openstack-creds
      become_user: "{{ user.name }}"

    - role: spotify
      tags: spotify
      become_user: "{{ user.name }}"

