---
- hosts: all
  become: yes
  roles:
    - role: base
      tags: base

    - role: packages
      tags: packages

    - role: laptop
      tags: laptop

    - role: display
      tags: display

    - role: gnome
      tags: gnome

    - role: sound
      tags: sound

    - role: android
      tags: android

    - role: tilix
      tags: tilix

    - role: networkmanager
      tags: networkmanager

    - role: macbook
      tags: macbook
      when: "'MacBook' in ansible_product_name"

#    - role: openstackclients
#      tags: openstackclients

    - role: ssh
      tags: ssh

    - role: vim
      tags: vim

    - role: user
      tags: user

    - role: aussieaddons
      tags: aussieaddons
      become_user: "{{ user.name }}"

#    - role: openstackcreds
#      tags: openstackcreds
#      become_user: "{{ user.name }}"

    - role: bluetooth
      tags: bluetooth

    - role: cups
      tags: cups

    - role: spotify
      tags: spotify
      become_user: "{{ user.name }}"

