---
- name: Install extra packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_extra }}"

- name: Install AUR extra packages
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  with_items: "{{ packages_aur }}"
