---
- name: Install display server packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - xorg
    - xorg-apps
    - mesa
    - libva-intel-driver  # vaapi
    - vulkan-intel
