---
- name: Install OpenSSH
  pacman:
    name: openssh
    state: present

- name: Create OpenSSH systemd unit file directory
  file:
    path: /etc/systemd/system/sshd.socket.d
    state: directory
  when: ssh.port is defined and ssh.port != 22

- name: Push OpenSSH socket unit file
  template:
    src: sshd-socket-override.conf.j2
    dest: /etc/systemd/system/sshd.socket.d/override.conf
  when: ssh.port is defined and ssh.port != 22
  notify:
    - reload systemd config
    - restart sshd

- name: Push OpenSSH daemon configuration file
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config

- name: Enable and start OpenSSH
  service:
    name: sshd.socket
    enabled: yes
    state: started
  when: ssh.enable_sshd == True

- name: Disable and stop OpenSSH
  service:
    name: sshd.socket
    enabled: no
    state: stopped
  when: ssh.enable_sshd == False
