---
- name: Push powersave script
  copy: src=powersave dest=/usr/local/bin/powersave mode=0755

- name: Push udev rules
  copy:
    src: "rules.d/{{ item }}"
    dest: "/etc/udev/rules.d/{{ item }}"
  with_items:
    - 50-powersave.rules
    - 50-powersave-pci.rules
    - 50-powersave-usb.rules

- name: Push powersave service file
  copy: src=systemd/powersave.service dest=/etc/systemd/system/powersave.service
  notify:
    - reload systemd config

- name: Enable and start powersave
  service: name=powersave.service enabled=yes state=started
