---
- name: Install GNOME desktop
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - gnome
    - gnome-extra
    - gnome-tweak-tool
    - gnome-power-manager
    - ttf-ubuntu-font-family

- name: Enable and start GDM
  service:
    name: gdm.service
    enabled: yes
