---
- name: Install OpenStack client packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ openstack_client_packages }}"

- name: Install OpenStack client packages from AUR
  pacaur:
    name: "{{ item }}"
  become_user: "{{ user.name }}"
  with_items: "{{ openstack_client_packages_aur }}"
