---
- name: Clone all projects
  git:
    repo: "git@github.com:aussieaddons/{{ item }}.git"
    dest: "{{ user.home }}/usr/projects/aussieaddons/{{ item }}"
    update: no
  with_items: "{{ (aussie_addons_addons + aussie_addons_extra) | unique }}"

- name: Set up Kodi symlinks
  file:
    src: "{{ user.home }}/usr/projects/aussieaddons/{{ item }}"
    dest: "{{ user.home }}/.kodi/addons/{{ item }}"
    state: link
  with_items: "{{ aussie_addons_addons }}"
