---
- name: Clone all projects
  git:
    repo: "git@github.com:xbmc-catchuptv-au/{{ item }}.git"
    dest: "{{ user.home }}/usr/projects/aussie-addons/{{ item }}"
    update: no
  with_items: "{{ aussie_addons_repos }}"

- name: Set up Kodi symlinks
  file:
    src: "{{ user.home }}/usr/projects/aussie-addons/{{ item }}"
    dest: "{{ user.home }}/.kodi/addons/{{ item }}"
    state: link
  with_items: "{{ aussie_addons_repos }}"
