---
- name: Remove old packages
  pacman:
    name: "{{ item }}"
    state: absent
  with_items:
    - gnome-terminal
    - vte3
    - vte-common

- name: Install Tilix
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  with_items:
    - vte-notification-common
    - vte3-notification
    - gnome-terminal-fedora
    - gtkd
    - tilix
