---
- name: Install Tilix
  pacman:
    name: "{{ item }}"
  with_items:
    - gtkd
    - tilix

#- name: Install VTE with notification patches
#  aur:
#    name: "{{ item }}"
#    user: "{{ user.name }}"
#  with_items:
#    - vte-notification-common
#    - vte3-notification
