---
- name: Remove vi
  pacman:  
    name: vi
    state: absent

- name: Install vim
  pacman:
    name: vim
    state: installed

- name: Set up vi to vim syntax
  aur:
    name: vi-vim-symlink
    user: "{{ user.name }}"

- name: System wide vimrc
  copy:
    src: vimrc
    dest: /etc/vimrc
