---
- name: Remove vi
  pacman:  
    name: vi
    state: absent
  with_items:
    - vi
    - vi-vim-symlink

- name: Install vim and plugins
  pacman:
    name: "{{ item }}"
    state: installed
  with_items:
    - vim-airline
    - vim-syntastic
    - powerline-fonts

- name: Make vim symlinks
  file:
    src: vim
    dest: "/usr/bin/{{ item }}"
    state: link
  with_items:
    - edit
    - ex
    - vedit
    - vi
    - view

- name: System wide vimrc
  copy:
    src: vimrc
    dest: /etc/vimrc

- name: User vimrc
  copy:
    src: user-vimrc
    dest: "{{ user.home }}/.vimrc"
  become: "{{ user.name }}"
