---
- name: Install ALSA packages
  pacman:
    name:
      - alsa-utils
    state: present

- name: Remove ALSA state daemon config
  file:
    path: /etc/alsa/state-daemon.conf
    state: absent

- name: Enable ALSA save/restore
  service:
    name: alsa-restore.service
    enabled: yes
