---
- name: Install NetworkManager and related packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - networkmanager
    - modemmanager
    - networkmanager-openvpn
    - usb_modeswitch
    - dnsmasq

- name: Set dnsmasq as DNS resolver
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    section: main
    option: dns
    value: dnsmasq
  notify:
    - restart NetworkManager

- name: Enable and start NetworkManager
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - NetworkManager.service
    - ModemManager.service
